[project]
name = "leofinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "duckdb>=1.4.2",
    "kagglehub>=0.3.9",
    "requests>=2.32.5",
    "torch>=2.9.1",
]
